apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: task-manager.dev
      http:
        paths:
          - path: /users/?(.*)
            backend:
              serviceName: task-manager-server-srv
              servicePort: 5000
          - path: /tasks/?(.*)
            backend:
              serviceName: task-manager-server-srv
              servicePort: 5000
          - path: /?(.*) # catch all at last
            backend:
              serviceName: client-srv
              servicePort: 3000
